---
#- name: install - create group
#  group:
#    name={{ terraform_group }}
#    system=yes
#
#- name: install - create user
#  user:
#    name={{ terraform_user }}
#    group={{ terraform_group }}
#    system=yes
#    createhome=no

